import{r as e}from"./assets/rolldown-runtime-Cq0jCQ29.js";import{n as t,r as n,t as r}from"./assets/vendor-DGJAgXav.js";(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin===`use-credentials`?t.credentials=`include`:e.crossOrigin===`anonymous`?t.credentials=`omit`:t.credentials=`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();var i=e(n(),1),a=e(t(),1),o=a.default.default||a.default,s=document.querySelector(`.gallery`),c=document.querySelector(`.loader`),l=document.querySelector(`.load-more`),u;function d(){l.classList.add(`active`)}function f(){l.classList.remove(`active`)}function p(){s.innerHTML=``}function m(){c.classList.add(`active`)}function h(){c.classList.remove(`active`)}function g(e){let t=e.map(({webformatURL:e,largeImageURL:t,tags:n,likes:r,views:i,comments:a,downloads:o})=>`
      <li class="gallery-item">
        <a href="${t}">
          <img src="${e}" alt="${n}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><span class="label">Likes:</span> <span class="value">${r}</span></p>
          <p class="info-item"><span class="label">Views:</span> <span class="value">${i}</span></p>
          <p class="info-item"><span class="label">Comments:</span> <span class="value">${a}</span></p>
          <p class="info-item"><span class="label">Downloads:</span> <span class="value">${o}</span></p>
        </div>
      </li>
    `).join(``);return s.insertAdjacentHTML(`beforeend`,t),u?u.refresh():u=new o(`.gallery a`,{captionsData:`alt`,captionDelay:250,showCounter:!0,nav:!0,close:!0,overlay:!0}),e.length}var _=`55082106-4cb46bb19233a000c0dff9eca`,v=`https://pixabay.com/api/`;async function y(e,t=1,n=15){let i=n<15?15:n;try{return(await r.get(v,{params:{key:_,q:e,image_type:`photo`,orientation:`horizontal`,safesearch:!0,page:t,per_page:i}})).data}catch(e){throw console.error(`Pixabay API error:`,e),e}}var b=document.querySelector(`.form`),x=document.querySelector(`.load-more`),S=b.elements[`search-text`],C=1,w=``;S.addEventListener(`input`,()=>{S.value.trim()||(f(),p())});async function T(e){let t=g(e.hits);if(C+=1,(C-1)*e.hits.length+t<e.totalHits?d():(f(),i.default.info({message:`We're sorry, but you've reached the end of search results.`})),t>0){let{height:e}=document.querySelector(`.gallery`).getBoundingClientRect();window.scrollBy({top:e*2,behavior:`smooth`})}}b.addEventListener(`submit`,async e=>{if(e.preventDefault(),w=S.value.trim(),!w){f(),p();return}C=1,f(),p(),m();try{let e=await y(w,C);if(!e.hits.length){i.default.error({message:`No images found!`}),f();return}await T(e)}catch(e){console.error(e),i.default.error({message:`Something went wrong!`})}finally{h()}}),x.addEventListener(`click`,async()=>{m(),f();try{let e=await y(w,C);if(!e.hits.length){i.default.info({message:`No more images to load!`});return}await T(e)}catch(e){console.error(e),i.default.error({message:`Something went wrong!`})}finally{h()}});
//# sourceMappingURL=index.js.map